### ISSUE TITLE
Handle nullRate and corruptedRate into DuzzyConfig

### ISSUE THREAD

**Issue by bhagenbourger** [bhagenbourger/duzzy#58]
Currently DuzzyConfig looks like:
```
---
enrichers:
  - query_selector: "name=city"
    provider_identifier: "io.duzzy.plugin.provider.random.AlphanumericRandomProvider"
    provider_parameters:
      min_length: 3
      max_length: 20
sink:
  identifier: "io.duzzy.plugin.sink.LocalFileSink"
  filename: "build/test.xml"
  serializer:
    identifier: "io.duzzy.plugin.serializer.XmlSerializer"
```

You could add fields parameters:
```
---
enrichers:
  - query_selector: "name=city"
     field_parameters:
       null_rate: 0.1
       corrupted_rate: 0.1
     provider_identifier: "io.duzzy.plugin.provider.random.AlphanumericRandomProvider"
     provider_parameters:
       min_length: 3
       max_length: 20
sink:
  identifier: "io.duzzy.plugin.sink.LocalFileSink"
  filename: "build/test.xml"
  serializer:
    identifier: "io.duzzy.plugin.serializer.XmlSerializer"
```
